### ISSUE TITLE
Rechter Schakelaar 1x aan/uit gedrukt cards don't fire

### ISSUE THREAD

**Issue by goyaweb** [caseda/com.tkbhome#19] opened 2017-03-19 17:08 UTC
Please let me know how I can debug this problem

**Comment by caseda** [comment] 2017-03-19 17:38
Tkb switches are not build for recognizing the 2 different switches inside the/a controller. 
Only for direct associations.

Even now/before only worked because of a massive workaround.
There is no way for you to debug this, and might not even be possible to fix it this time inside homey. 

Will have a look though.. 
But don't have your hopes up high

**Comment by goyaweb** [comment] 2017-03-19 17:41
ah but the massive workaround never worked for me either apparently. Does it still work for you?

**Comment by caseda** [comment] 2017-03-19 17:44
i don't use the tkb switch myself because of the way it works.. (really short dimming range when doing it manually)

can be that the workaround (that did work for me while testing) be a cause of a bug that snuck in 1.1.9 (homey core) that is used for the workaround.
so probably not fixable at least until that bug is squashed 

did you change your associations?

**Comment by goyaweb** [comment] 2017-03-19 17:47
so as a workaround do you think I could associate it to an unused fibaro relay and use the fibaro as a flow trigger?

The reason I use the TKB dimmer exclusively (for dimmer) because of it's intuitive way of dimming (hold press up and hold press down, couldn't get that behavior with fibaro or qubino)

**Comment by caseda** [comment] 2017-03-19 18:01
if it is a single relay then it should be possible, double relays you need to assign which relay needs to switch which is not yet possible in homey,, have been giving people that as a workaround if they ever want to use tkb

it is a intuitive way, but unfortunately tkb choose the route of it being a controller itself and not a switch and rely on the controller it can be attached to as well.
it is indeed not possible with fibaro or any other modules that have an output, since they all only have a max 2 inputs that can be either on or off, no possibility of a 3 way switch. (up/idle/down)
as for tkb it's just 4 separate buttons on the module itself.

**Comment by goyaweb** [comment] 2017-03-19 18:12
hmm only have unused fibaro and qubino double relays. Would 1.2 fix it maybe?

**Comment by caseda** [comment] 2017-03-19 20:29
Have not seen any messages that it will be (/have been) added to the core, so don't know/don't think so

**Comment by caseda** [comment] 2017-04-01 15:28
the not triggering on right switch should be fixed in 1.0.3. (now waiting approval in the app-store)

do please make sure your association groups are set with homey's id (only group 2 and group 3)

**Comment by caseda** [comment] 2017-04-30 18:22
can you confirm that it works again?

**Comment by caseda** [comment] 2017-05-20 13:16
Due to not answering, assuming that it works here too, closing the issue now.

if it still does not work, your are allowed to re-open the issue.

**Comment by goyaweb** [comment] 2017-11-12 16:58
Net getest maar werkt helaas nog niet. Dit is mijn configuratie:
<img width="769" alt="tkb home right switch" src="https://user-images.githubusercontent.com/783727/32701279-f0bc692e-c7d2-11e7-9b3f-eb21c9d2ca45.png">

**Comment by goyaweb** [comment] 2017-11-15 11:39
Ok, het volgende uitgevonden:
Als je 1x klikt dan wordt de kaart "rechts 2x aan geschakeld" gerund!
Het werkt dus wel alleen is de actie aan verkeerde kaart gekoppeld.

**Comment by caseda** [comment] 2017-11-15 11:44
Then you've got a strange (defective?) device, I check the 1x push vs 2x push if the NIF (node information frame) is send along, which it does for both buttons (left and right) when you press once, doesn't matter if it is the on or off side either.

Can you give a zwave log (settings -> zwave -> stuff for geeks) after you pressed once, and after a several seconds press it double

**Comment by caseda** [comment] 2018-01-20 13:16
as again no responds from OP, closing this issue

**Closed as completed by caseda** 2018-01-20 13:16 UTC

**Comment by goyaweb** [comment] 2018-01-20 13:35
2018-01-20T13:30:54.791Z | Node[20]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
-- | --
2018-01-20T13:30:54.797Z | Node[20]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
2018-01-20T13:30:54.844Z | Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
2018-01-20T13:30:54.844Z | Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
2018-01-20T13:30:57.329Z | Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_GET] {"type":"Buffer","data":[]}
2018-01-20T13:30:57.329Z | Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x02
2018-01-20T13:30:57.454Z | Node[20]: Received application command for COMMAND_CLASS_SWITCH_MULTILEVEL, data: 0x032e
2018-01-20T13:30:57.454Z | Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] {"Value (Raw)":{"type":"Buffer","data":[46]},"Value":{}}
2018-01-20T13:31:08.304Z | Node[20]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
2018-01-20T13:31:08.305Z | Node[20]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
2018-01-20T13:31:08.342Z | Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
2018-01-20T13:31:08.342Z | Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
2018-01-20T13:31:10.829Z | Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_GET] {"type":"Buffer","data":[]}
2018-01-20T13:31:10.829Z | Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x02
2018-01-20T13:31:11.229Z | Node[20]: Received application command for COMMAND_CLASS_SWITCH_MULTILEVEL, data: 0x032e
2018-01-20T13:31:11.230Z | Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] {"Value (Raw)":{"type":"Buffer","data":[46]},"Value":{}}

**Comment by caseda** [comment] 2018-01-20 14:36
I don't see any "application update" coming from your device, has this been filtered out?

**Comment by goyaweb** [comment] 2018-01-21 19:10
here it is unfiltered:

[2018-01-20T13:30:54.791Z] Node[20]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
[2018-01-20T13:30:54.797Z] Node[20]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
[2018-01-20T13:30:54.842Z] Node[48]: [COMMAND_CLASS_THERMOSTAT_SETPOINT] [THERMOSTAT_SETPOINT_SET] {"type":"Buffer","data":[1,34,0,190]}
[2018-01-20T13:30:54.844Z] Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
[2018-01-20T13:30:54.844Z] Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
[2018-01-20T13:30:54.847Z] Command[19002] start: sendData
[2018-01-20T13:30:54.848Z] ProcessSendData[19002]: To node: 20 with data: 0x2601ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:30:54.935Z] Command[19002] end: sendData
[2018-01-20T13:30:57.329Z] Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_GET] {"type":"Buffer","data":[]}
[2018-01-20T13:30:57.329Z] Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x02
[2018-01-20T13:30:57.334Z] Command[19003] start: sendData
[2018-01-20T13:30:57.334Z] ProcessSendData[19003]: To node: 20 with data: 0x2602 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:30:57.342Z] Command[19003] end: sendData
[2018-01-20T13:30:57.454Z] Node[20]: Received application command for COMMAND_CLASS_SWITCH_MULTILEVEL, data: 0x032e
[2018-01-20T13:30:57.454Z] Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] {"Value (Raw)":{"type":"Buffer","data":[46]},"Value":{}}
[2018-01-20T13:30:59.813Z] Node[7]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
[2018-01-20T13:30:59.813Z] Node[7]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
[2018-01-20T13:30:59.816Z] Command[19004] start: sendData
[2018-01-20T13:30:59.816Z] ProcessSendData[19004]: To node: 7 with data: 0x2601ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:30:59.883Z] Command[19004] end: sendData
[2018-01-20T13:31:01.195Z] Node[23]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_GET] {"type":"Buffer","data":[]}
[2018-01-20T13:31:01.195Z] Node[23]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x02
[2018-01-20T13:31:01.195Z] Command[19005] start: sendData
[2018-01-20T13:31:01.196Z] ProcessSendData[19005]: To node: 23 with data: 0x2502 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:01.199Z] Node[24]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_GET] {"type":"Buffer","data":[]}
[2018-01-20T13:31:01.199Z] Node[24]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x02
[2018-01-20T13:31:01.343Z] Command[19005] end: sendData
[2018-01-20T13:31:01.344Z] Command[19006] start: sendData
[2018-01-20T13:31:01.344Z] ProcessSendData[19006]: To node: 24 with data: 0x2502 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:01.465Z] Node[23]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2018-01-20T13:31:01.465Z] Node[23]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
[2018-01-20T13:31:01.569Z] Node[23]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2018-01-20T13:31:01.570Z] Node[23]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
[2018-01-20T13:31:01.803Z] Node[23]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2018-01-20T13:31:01.803Z] Node[23]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
[2018-01-20T13:31:01.930Z] Command[19006] end: sendData
[2018-01-20T13:31:01.980Z] Node[24]: Received application command for COMMAND_CLASS_SWITCH_BINARY, data: 0x03ff
[2018-01-20T13:31:01.980Z] Node[24]: [COMMAND_CLASS_SWITCH_BINARY] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":"on/enable"}
[2018-01-20T13:31:08.304Z] Node[20]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
[2018-01-20T13:31:08.305Z] Node[20]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
[2018-01-20T13:31:08.342Z] Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
[2018-01-20T13:31:08.342Z] Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
[2018-01-20T13:31:08.343Z] Command[19007] start: sendData
[2018-01-20T13:31:08.343Z] ProcessSendData[19007]: To node: 20 with data: 0x2601ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:08.354Z] Node[48]: [COMMAND_CLASS_THERMOSTAT_SETPOINT] [THERMOSTAT_SETPOINT_SET] {"type":"Buffer","data":[1,34,0,190]}
[2018-01-20T13:31:08.446Z] Command[19007] end: sendData
[2018-01-20T13:31:09.814Z] Node[4]: [COMMAND_CLASS_SWITCH_BINARY] [SWITCH_BINARY_SET] {"type":"Buffer","data":[255]}
[2018-01-20T13:31:09.814Z] Node[4]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x01ff
[2018-01-20T13:31:09.817Z] Command[19008] start: sendData
[2018-01-20T13:31:09.817Z] ProcessSendData[19008]: To node: 4 with data: 0x2501ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:09.980Z] Command[19008] end: sendData
[2018-01-20T13:31:10.006Z] Node[16]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[16,1,38,1,255]}
[2018-01-20T13:31:10.007Z] Node[16]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d10012601ff
[2018-01-20T13:31:10.010Z] Command[19009] start: sendData
[2018-01-20T13:31:10.010Z] ProcessSendData[19009]: To node: 16 with data: 0x600d10012601ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:10.064Z] Command[19009] end: sendData
[2018-01-20T13:31:10.773Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:10.774Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:10.787Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:10.787Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:10.829Z] Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_GET] {"type":"Buffer","data":[]}
[2018-01-20T13:31:10.829Z] Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x02
[2018-01-20T13:31:10.830Z] Command[19010] start: sendData
[2018-01-20T13:31:10.830Z] ProcessSendData[19010]: To node: 20 with data: 0x2602 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:10.838Z] Command[19010] end: sendData
[2018-01-20T13:31:10.854Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:10.854Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:10.867Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:10.868Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:11.229Z] Node[20]: Received application command for COMMAND_CLASS_SWITCH_MULTILEVEL, data: 0x032e
[2018-01-20T13:31:11.230Z] Node[20]: [COMMAND_CLASS_SWITCH_MULTILEVEL] {"Value (Raw)":{"type":"Buffer","data":[46]},"Value":{}}
[2018-01-20T13:31:11.336Z] Node[4]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000003f0000
[2018-01-20T13:31:11.338Z] Node[4]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,63]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":6.3}
[2018-01-20T13:31:11.490Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:11.491Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:11.502Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:11.502Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:11.518Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:11.518Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:11.537Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:11.538Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:12.056Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:12.056Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:12.069Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:12.070Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:12.126Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:12.126Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:12.139Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:12.139Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:12.337Z] Node[4]: Received application command for COMMAND_CLASS_METER, data: 0x022134000000510000
[2018-01-20T13:31:12.338Z] Node[4]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[52]},"Properties2":{"Size":4,"Scale bits 10":2,"Precision":1},"Meter Value":{"type":"Buffer","data":[0,0,0,81]},"Delta Time (Raw)":{"type":"Buffer","data":[0,0]},"Delta Time":0,"Meter Value (Parsed)":8.1}
[2018-01-20T13:31:12.422Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:12.423Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:12.442Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:12.442Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:12.471Z] Node[8]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x01300300cf3b
[2018-01-20T13:31:12.472Z] Node[8]: [COMMAND_CLASS_CRC_16_ENCAP] {"Command Class (Raw)":{"type":"Buffer","data":[48]},"Command Class":48,"Command (Raw)":{"type":"Buffer","data":[3]},"Command":3,"Data":{"type":"Buffer","data":[0]},"Checksum (Raw)":{"type":"Buffer","data":[207,59]},"Checksum":53051}
[2018-01-20T13:31:12.485Z] Node[8]: [COMMAND_CLASS_SENSOR_BINARY] {"Sensor Value (Raw)":{"type":"Buffer","data":[0]},"Sensor Value":"idle"}
[2018-01-20T13:31:12.485Z] Node[8]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_BINARY, data 0x0300
[2018-01-20T13:31:13.316Z] Node[7]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
[2018-01-20T13:31:13.316Z] Node[7]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
[2018-01-20T13:31:13.316Z] Command[19011] start: sendData
[2018-01-20T13:31:13.317Z] ProcessSendData[19011]: To node: 7 with data: 0x2601ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:13.372Z] Command[19011] end: sendData
[2018-01-20T13:31:13.813Z] Node[5]: [COMMAND_CLASS_SWITCH_MULTILEVEL] [SWITCH_MULTILEVEL_SET] {"type":"Buffer","data":[255]}
[2018-01-20T13:31:13.813Z] Node[5]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x01ff
[2018-01-20T13:31:13.814Z] Command[19012] start: sendData
[2018-01-20T13:31:13.814Z] ProcessSendData[19012]: To node: 5 with data: 0x2601ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-20T13:31:13.901Z] Command[19012] end: sendData

**Comment by caseda** [comment] 2018-01-21 20:35
then that is the cause of not triggering, your device is not sending the NIF (application update) when pressing ones.

without that it is impossible to see if the user only has pressed once, or twice.

even though it is odd that it is getting the current output level (Node[20]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x02), which is also only called when the NIF is send (for seeing if the left or right switch is press). 🤔

makes it look like the same issue as #27
which device are you actually referring too?

**Comment by caseda** [comment] 2018-01-22 09:55
Bump for the edited in question:
which device is the issue about?

Also the TZ66?
If so then that device works differently then the rest.

**Comment by goyaweb** [comment] 2018-01-22 14:11
I've got a TZ65D
